<!DOCTYPE html>
<html>
<head>
	<title>Registro</title>
</head>
<body>
<h1>Registro</h1>
<form action="index.php?user" method="post">
	<input type="text" name="newNombre" placeholder="Nombre de usuario" required>
	<input type="password" name="pass1" placeholder="Contraseña" required>
	<input type="password" name="pass2" placeholder="Repite la Contraseña" required>
	<input type="submit" value="Registrar">

</form>
</body>
</html>